set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g mouse on
set -g history-limit 10000
set-option -g set-titles off
set-option -g set-titles-string '#T'
#set -g status-left-length 60
#set -g status-right-length 60
#set -g status-left "#[fg=magenta,bg=default]#[fg=white,bg=magenta] #(whoami)@#h #[fg=magenta,bg=brightblack]#[fg=white,bg=brightblack] #(current_cmd #{pane_pid} #{pane_current_command}) #[fg=brightblack,bg=default]"
#set -g status-right "#[fg=green,bg=default]#[fg=white,bg=green] #(loadavg) #[fg=brightblack,bg=green]#[fg=yellow,bg=brightblack] #(memavail) #[fg=blue,bg=brightblack]#[fg=white,bg=blue] %H:%M #[fg=blue,bg=default]"
set -g window-status-current-format "#[fg=magenta,bg=default]#[fg=white,bg=magenta] #(whoami)@#h #[fg=magenta,bg=blue]#[fg=white,bg=blue] #T #[fg=blue,bg=brightblack]#[fg=white,bg=brightblack] #(current_cmd) #[fg=cyan,bg=brightblack]#[fg=white,bg=cyan] #(usercount) #[bg=cyan,fg=green]#[fg=white,bg=green] #(loadavg) #[fg=brightblack,bg=green]#[fg=yellow,bg=brightblack] #(memavail) #[fg=blue,bg=brightblack]#[fg=white,bg=blue] %H:%M #[fg=blue,bg=default]"

# If tmux supports 'status-style' (new versions)
if-shell -b 'tmux show -g | grep -q status-style' \
    'set -g status-style "bg=colour235"'

set -g status-bg "colour235"
set -g status-justify centre
set -g status-position top
set -g status-left ''
set -g status-right ''
#set -g status ''
#set -g status-format[0] "#[align=centre]#S"

#set-option -g default-command 'cd $FLY_HOME/.fly.d/.fly.lib;exec bash --rcfile .bashrc'
set-option -g default-command 'bash -c ". $FLY_HOME/.fly.d/fly loginshell"'
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',*:Tc'
set -sg escape-time 0

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-m if-shell '[ "$(tmux show -gv mouse)" = "on" ]' \
  'set -g mouse off' \
  'set -g mouse on'

bind -n M-v paste-buffer
bind -n M-z resize-pane -Z
bind -n C-Down split-window -v
bind -n C-Right split-window -h
bind -n M-r source-file .tmux.conf
bind -n C-x send-keys C-c
bind -n M-Enter send-keys C-m
bind -n Insert send-keys C-m


# To Fuck CyberAss !!!  bind -n C-C refresh-client

set-option -g word-separators " ?@;[]{}()─"
bind-key -T root MouseDown3Pane paste-buffer
bind-key    -T root         C-MouseDown1Pane         if-shell -F -t = "#{||:#{mouse_any_flag},#{&&:#{pane_in_mode},#{?#{m/r:(copy|view)-mode,#{pane_mode}},0,1}}}" { select-pane -t = ; send-keys -M } { display-menu -T "#[align=centre]#{pane_index} (#{pane_id})" -t = -x M -y M "#{?#{m/r:(copy|view)-mode,#{pane_mode}},Go To Top,}" < { send-keys -X history-top } "#{?#{m/r:(copy|view)-mode,#{pane_mode}},Go To Bottom,}" > { send-keys -X history-bottom } '' "#{?mouse_word,Search For #[underscore]#{=/9/...:mouse_word},}" C-r { if-shell -F "#{?#{m/r:(copy|view)-mode,#{pane_mode}},0,1}" "copy-mode -t=" ; send-keys -X -t = search-backward "#{q:mouse_word}" } "#{?mouse_word,Type #[underscore]#{=/9/...:mouse_word},}" C-y { copy-mode -q ; send-keys -l "#{q:mouse_word}" } "#{?mouse_word,Copy #[underscore]#{=/9/...:mouse_word},}" c { copy-mode -q ; set-buffer "#{q:mouse_word}" } "#{?mouse_line,Copy Line,}" l { copy-mode -q ; set-buffer "#{q:mouse_line}" } '' "#{?mouse_hyperlink,Type #[underscore]#{=/9/...:mouse_hyperlink},}" C-h { copy-mode -q ; send-keys -l "#{q:mouse_hyperlink}" } "#{?mouse_hyperlink,Copy #[underscore]#{=/9/...:mouse_hyperlink},}" h { copy-mode -q ; set-buffer "#{q:mouse_hyperlink}" } '' "Horizontal Split" h { split-window -h } "Vertical Split" v { split-window -v } '' "#{?#{>:#{window_panes},1},,-}Swap Up" u { swap-pane -U } "#{?#{>:#{window_panes},1},,-}Swap Down" d { swap-pane -D } "#{?pane_marked_set,,-}Swap Marked" s { swap-pane } '' Kill X { kill-pane } Respawn R { respawn-pane -k } "#{?pane_marked,Unmark,Mark}" m { select-pane -m } "#{?#{>:#{window_panes},1},,-}#{?window_zoomed_flag,Unzoom,Zoom}" z { resize-pane -Z } }

